spring:
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    enabled: true
    drop-first: false
    contexts: dev
    default-schema: public
  docker:
    compose:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.catalina: INFO
    lynx.com: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.boot.autoconfigure.liquibase: INFO
    liquibase: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr([%X{traceId}]){red} %clr(%-5level){highlight} %clr(%logger{36}){blue} %clr(-){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app-dev.log

server:
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access
      suffix: .log
      pattern: "%h %l %u %t \"%r\" %s %b"
